### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by timstarkk** [pixelfear/Statamic-Randomize#1]
There are no instructions on how to use on my project. Thanks.

**Comment by jasonvarga** [comment]
The readme shows how to use it.

This is for Statamic v1 though.

**Comment by timstarkk** [comment]
Thanks it just doesn't show how to add to my project sorry.

**Comment by jasonvarga** [comment]
https://v1.statamic.com/learn/using-add-ons/installing
